name: Tests

on: [pull_request]

jobs: 
    tests:
        name: Tests
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup PHP Environment
            run: |
                docker build . -t php8-env
                docker run -d --name tests php8-env 

          - name: Run Analyze
            run: docker exec tests composer analyze
          
          - name: Run Tests
            run: docker exec tests composer test
          


