name: Tests

on: [pull_request]

jobs: 
    tests:
        name: Tests
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup PHP
            uses: shivammathur/setup-php@2.25.5
            with: 
              php-version: '8.0'
        
          - name: Composer Install
            run: composer install --ignore-platform-reqs
          
          - name: Run Tests
            run: composer test

